name: build-wheels

on:
  push:
    branches:
    - master
    - manylinux-wheel
  pull_request:
    branches:
    - master

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          # - windows-2019
          # - macos-10.15
    env:
      LIBPOSTAL_GIT_TAG: "9c975972985b54491e756efd70e416f18ff97958"
      LIBPOSTAL_DEPS_DIR: "/tmp/libpostal-deps"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Cache libpostal
      uses: actions/cache@v2
      with:
        path: |
          ~/libpostal
        key: ${{ runner.os }}-${{ env.LIBPOSTAL_GIT_TAG }}

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.1.3

    - name: Install libpostal
      run: |
        sudo apt-get install curl autoconf automake libtool pkg-config
        git clone https://github.com/openvenues/libpostal
        cd libpostal
        git checkout "${{ env.LIBPOSTAL_GIT_TAG }}"
        ./bootstrap.sh
        ./configure \
          --datadir="$(pwd)/datadir" \
          --prefix="${{ env.LIBPOSTAL_DEPS_DIR }}" \
          --bindir="${{ env.LIBPOSTAL_DEPS_DIR }}" \
          --disable-data-download
        sudo make install

    - name: Build wheels
      env:
        CFLAGS: "-I${{ env.LIBPOSTAL_DEPS_DIR }}/include"
        LDFLAGS: "-L${{ env.LIBPOSTAL_DEPS_DIR }}/lib"
      run: python -m cibuildwheel --output-dir wheelhouse
    - run: |
        ls -l wheelhouse/

    # - name: Build libpostal
    #   run: |
    #     pushd libpostal-image/
    #     docker build -t openvenues/libpostal .
    #     popd
    # # TODO: Cache built image + datadir (if we download it).
    # - name: Build wheels
    #   run: |
    #     docker run --rm \
    #       --volume `pwd`:/io openvenues/libpostal \
    #       /io/build-wheels.sh
    #     ls -lh wheelhouse/
    # - name: Test wheels
    #   # TODO: The datadir needs to be provided somehow, either
    #   # by bundling it in with the wheels, or by enabling pypostal
    #   # to download it on first execution.
    #   run: |
    #     docker run --rm \
    #       --volume `pwd`:/io \
    #       --volume TODO-provide-datadir:/datadir \
    #       python:3.9 /io/test-wheels.sh

# TODO: Publish wheels to some sort of repository.
